local cfg = {}

cfg.items = {
  	["seeds"] = {"Seeds", "Niste seminte de iarba.", nil, 0.1,"pocket"},
  	["credit"] = {"Card-uri de Credit Furate", "Card-uri de Credit furate care pot fi transformate in Buletine Ilegale la Falsificator.", nil, 0.2,"pocket"},
  	["bank_money"] = {"Bani de Banca", "$.", nil, 0,"pocket"},
  	["trash"] = {"Gunoi", "Pute a hoit!", nil, 0,"pocket"},
  	["fake_id"] = {"Buletin Falsificat", "Scrie un nume pe el Hmmm...", nil, 0,"pocket"},
	["cigarette"] = {"Tigara cu Ciuperci","Tigari cu ciuperci pentru viata usoara.", nil,0.1,"pocket"},
	["AK47"] = {"AK47", "Un masterpeice de Rusia.", nil, 0.4,"pocket"},
	["DB"] = {"Deagle", "Deagle", nil, 0.4,"pocket"},
	["M4A1"] = {"M4A1", "Un masterpiece de America.", nil, 0.4,"pocket"},
	["peste"] = {"Peste", "Peste mic gasit in mare", nil, 1.0},
	["rinichi"] = {"Rinichi", "", nil, 0.4,"pocket"},
	["inima"] = {"Inima", "", nil, 0.4,"pocket"},
	["ficat"] = {"Ficat", "", nil, 1.0},
	["ciuperca"] = {"Ciuperci", "Ciuperca pentru vanzare..", nil, 1.0},
	["oilcan"] = {"Canistra de ulei", "Deseu", nil, 0},
	["shoe"] = {"Cizma", "O fi cizma lui Jack Sparrow?", nil, 0},
	["secure_card"] = {"Card de Securitate", "Acest card se foloseste pentru jafuri", nil, 1.0},
	["cashbag"] = {"Punga cu bani uzi", "Ce idiot", nil, 0},
	["asigurare"] = {"Asigurare", "Asigurare Auto", nil, 0},
	["fishingrod"] = {"Undita", "Foloseste-o numai pe malul apei", nil, 0.01},
	["momealapeste"] = {"Momeala", "Ar trebui sa prinda ceva", nil, 0.01},
	["foarfece"] = {"Foarfece", "Foarfeca pentru jobul de ciupercar", nil, 0.01},
	---- AICI AM RAMAS CU ICONITELE -------  
	["minereudiamant"] = {"Minereu Diamant", "Pentru jobul de miner", nil, 0,"pocket"},
	["minereusulf"] = {"Minereu Sulf", "Pentru jobul de miner", nil, 0,"pocket"},
	["minereuaur"] = {"Minereu Aur", "Pentru jobul de miner", nil, 0,"pocket"},
	["minereucarbune"] = {"Minereu Carbune", "Pentru jobul de miner", nil, 0,"pocket"},
	["minereuargint"] = {"Minereu Argint", "Pentru jobul de miner", nil, 0,"pocket"},
	["minereufier"] = {"Minereu Fier", "Pentru jobul de miner", nil, 0,"pocket"},
	["inelcudiamant"] = {"Inel cu Diamant", "Pentru jobul de miner", nil, 0,"pocket"},
	["conserva"] = {"Conserva", "Pentru jobul de miner", nil, 0,"pocket"},
	["pickaxe"] = {"Pickaxe", "Pentru jobul de miner", nil, 0,"pocket"},
	["plastic"] = {"Plastic", "Pentru jobul de miner", nil, 0,"pocket"},
	["shoe"] = {"Cizma", "O fi cizma lui Jack Sparrow?", nil, 0,"pocket"},
	["cashbag"] = {"Punga cu bani uzi", "Ce idiot", nil, 0,"pocket"},
	["oilcan"] = {"Canistra de ulei", "Deseu", nil, 0,"pocket"},
	["tank"] = {"Minereu", "Pentru jobul de miner", nil, 0,"pocket"},
	["shoe"] = {"Cizma", "O fi cizma lui Jack Sparrow?", nil, 0,"pocket"},
	["cashbag"] = {"Punga cu bani uzi", "Ce idiot", nil, 0,"pocket"},
	["picamer"] = {"Picamer", "Picamer pentru constructor", nil, 0,"pocket"},
	["ciocan"] = {"Ciocan", "Ciocan pentru jobul de constructor", nil, 0,"pocket"},
	["lighter"] = {"Bricheta", "O bricheta tip vintage",nil,0.5,"pocket"},
	["gold_bar"] = {"Lingou de Aur", "Un lingou de aur pur!",nil,0,"pocket"},
	["lockpick_tools"] = {"Unelte Incuietori", "Unelte pentru a sparge incuietorile usilor.", nil, 0.2,"pocket"},
	["trusa"] = {"Trusa","Obiecte preferate pentru minerit",nil,0.4,"pocket"},
	["pet"] = {"Sticla Goala","Bun pentru depozitare bauturi!",nil,0.1,"pocket"},
	["aphone"] = {"Telefon Mobil", "Call and send SMS.", nil, 0,"pocket"},
	["photosm"] = {"Poza Mixta","Poza cu cu peisaj urban si natural combinat!",nil,0.1,"pocket"},
	["samanta"] = {"Samanta de rosie","Gustul bun de rosie vine de la o samanta buna!",nil,0.1,"pocket"},
	["revista"] = {"Revista Natura","O revista incantatoare care ajuta oameni sa se relaxeze citindo!",nil,0.1,"pocket"},
	["ziar"] = {"Ziar","Un ziar care aduce multe stiri societatii!",nil,0.1,"pocket"},
	["fier"] = {"Fier","Minereu de fier",nil,0.0,"pocket"},
	["cupru"] = {"Cupru","Cupru",nil,0.0,"pocket"},
	["sulf"] = {"Sulf","Sulf",nil,0.0,"pocket"},
	["prafdepusca"] = {"Praf de Pusca","Praf de Pusca",nil,0.0,"pocket"},
	["amethyst"] = {"Amethyst","Piatra pretioasa",nil,0.6,"pocket"},
	["safir"] = {"Safir","Piatra foarte pretioasa",nil,0.6,"pocket"},
	["uranium"] = {"Uranium","Radioactivitatea ei creaza haos",nil,0.6,"pocket"},
	["aur"] = {"Aur","Metal Pretios foarte valoros",nil,0.6,"pocket"},
	["diamant"] = {"Diamant","Diamant foarte pretios si foarte valoros, INDESTRUCTIBIL",nil,0.6,"pocket"},
	["id_doc"] = {"Buletin","Un buletin cu numele si informatiile tale pe el! Nu il pierde",nil,0,"pocket"},
	["gunpermit_doc"] = {"Permis Port-Arma","Un permis ce te lasa sa ai asupra ta arme de foc",nil,0,"pocket"},
	["hash_token_rocketcasino"] = {"Moneda Cazino","Moneda cu care poti juca la cazino",nil,0,"pocket"},
	["asigurare_masina"] = {"Asigurare de Masina","O Asigurare de masina pe care o puteti oferi la altii sau pastra pentru masina voastra",nil,0,"pocket"},
	["dosardmv"] = {"Dosar DMV","Cu acest item te duci la un politist pentru a da de permis, el te va verifica daca ai dosar sau nu.",nil,0,"pocket"},
	["thermal_charge"] = {"Thermal", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.8,"pocket"},
	["laptop_h"] = {"Laptop", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.8,"pocket"},
	["lockpick"] = {"Lockpick", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.8,"pocket"},
	["id_card"] = {"Id Card", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.8,"pocket"},
	["bijuterii"] = {"Bijuterii pretioase","",nil,0.2},
	["gold_bar"] = {"Gold Bar", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.8,"pocket"},
	["combomeal"] = {"Combo Meal", "Mc Donalds",nil,0.8,"pocket"},
	["bigmac"] = {"Big Mac", "Mc Donalds",nil,0.8,"pocket"},
	["mcpollo"] = {"Mc pollo", "Mc Donalds",nil,0.8,"pocket"},
	["mcroyaldeluxe"] = {"Royal Deluxe ", "Mc Donalds",nil,0.8,"pocket"},
	["cbo"] = {"CBO", "Mc Donalds",nil,0.8,"pocket"},
	["cuartodelibra"] = {"Cuarto de Libra", "Mc Donalds",nil,0.8,"pocket"},
	["grandmcextreme"] = {"Grand McExtreme Bacon Burger", "Mc Donalds",nil,0.8,"pocket"},
	["bigchickensupreme"] = {"Big Chicken Supreme", "Mc Donalds",nil,0.8,"pocket"},
	["bigcrispybbq"] = {"Big Crispy BBQ", "Mc Donalds",nil,0.8,"pocket"},
	["bigdoublecheese"] = {"Big Double Cheese", "Mc Donalds",nil,0.8,"pocket"},
	["hamburgesa"] = {"Hamburger", "Mc Donalds",nil,0.8,"pocket"},
	["cristalcocaina"] = {"Cristal Cocaina", "Cristale ilegale",nil,0.5,"pocket"},
    ["cristalheroina"] = {"Cristal Heroina", "Cristale ilegale",nil,0.7,"pocket"},
	["drug_cansativa"] = {"Cannabis Sativa", "Esenta de canabis folosita pentru crearea drogurilor puternice",nil,0.5,"pocket"},
	["drug_cocaalka"] = {"Cocaina Alkaloid", "Un lighid albastru extras din planta coca",nil,0.7,"pocket"},
	["drug_unprocpcp"] = {"PCP Neprocesat", "Praf alb de PCP neprocesat",nil,0.6,"pocket"},
	["drug_lyseracid"] = {"Acid Lysergic", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.8,"pocket"},
    ["iarba"] = {"Cristal Heroina", "Cristale ilegale",nil,0.5,"pocket"},
    ["stack_iarba"] = {"Cannabis Sativa", "Esenta de canabis folosita pentru crearea drogurilor puternice",nil,4,"pocket"},
    ["cocaina"] = {"Cocaina Alkaloid", "Un lighid albastru extras din planta coca",nil,0.5,"pocket"},
    ["stack_cocaina"] = {"PCP Neprocesat", "Praf alb de PCP neprocesat",nil,4,"pocket"},
    ["metanfetamina"] = {"Acid Lysergic", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.5,"pocket"},
    ["stack_metanfetamina"] = {"Acid Lysergic", "Substanta puternica din seminte de Turbina Corymbosa",nil,4,"pocket"},
	["hamburgesadepollo"] = {"Hamburger pollo", "Mc Donalds",nil,0.8,"pocket"},
	["mcfish"] = {"Mc Fish", "Mc Donalds",nil,0.8,"pocket"},
	["happymeal"] = {"Happy Meal", "Mc Donalds",nil,0.8,"pocket"},
	["cocacola"] = {"Coca Cola", "Mc Donalds",nil,0.8,"pocket"},
	["nestea"] = {"Nestea", "Mc Donalds",nil,0.8,"pocket"},
	["agua"] = {"Apa", "Mc Donalds",nil,0.8,"pocket"},
	["monsterenergy"] = {"Monster Energy", "Mc Donalds",nil,0.8,"pocket"},
	["aquarius"] = {"Apa", "Mc Donalds",nil,0.8,"pocket"},
	["cerveza"] = {"Cerveza", "Mc Donalds",nil,0.8,"pocket"},
	["sprite"] = {"Sprite", "Mc Donalds",nil,0.8,"pocket"},
	["nuggets"] = {"Nuggets", "Mc Donalds",nil,0.8,"pocket"},
	["patatasfritas"] = {"Cartofi", "Mc Donalds",nil,0.8,"pocket"},
	["topfries"] = {"Top Fries", "Mc Donalds",nil,0.8,"pocket"},
	["fanta"] = {"Fanta", "Mc Donalds",nil,0.8,"pocket"},

	["scanner"] = {"Scanner", "", nil, 0},
	['oil'] = {'Engine oil', "", nil, 0},
	['tires'] = {'Tires', "", nil, 0},
	['brake_pads'] = {'Brake pads', "", nil, 0},
	['transmission_oil'] = {'Transmission oil', "", nil, 0},
	['shock_absorber'] = {'Shock absorber', "", nil, 0},
	['clutch'] = {'Clutch', "", nil, 0},
	['air_filter'] = {'Air filter', "", nil, 0},
	['fuel_filter'] = {'Fuel filter', "", nil, 0},
	['spark_plugs'] = {'Spark plugs', "", nil, 0},
	['serpentine_belt'] = {'Serpentine belt', "", nil, 0},
	['susp'] = {'Lowered suspension', "", nil, 0},
	['susp1'] = {'Stanced suspension', "", nil, 0},
	['susp2'] = {'Sport suspension', "", nil, 0},
	['susp3'] = {'Confort suspension', "", nil, 0},
	['susp4'] = {'Lifted suspension', "", nil, 0},
	['garett'] = {'Garett GTW Turbo', "", nil, 0},
	['nitrous'] = {'Nitro', "", nil, 0},
	['AWD'] = {'AWD swap', "", nil, 0},
	['RWD'] = {'RWD swap', "", nil, 0},
	['FWD'] = {'FWD swap', "", nil, 0},
	['semislick'] = {'Semi Slick tires', "", nil, 0},
	['slick'] = {'Slick tires', "", nil, 0},
	['race_brakes'] = {'Brembo brakes', "", nil, 0},
	['piston'] = {'Piston', "", nil, 0},
	['rod'] = {'Rod', "", nil, 0},
	['gear'] = {'Gear', "", nil, 0},
	['brake_discs'] = {'Brake disc', "", nil, 0},
	['brake_caliper'] = {'Brake caliper', "", nil, 0},
	['springs'] = {'Springs', "", nil, 0},
	['iron'] = {'Iron', "", nil, 0},
	['aluminum'] = {'Aluminum', "", nil, 0},
}

local function load_item_pack(name)
  local items = module("cfg/item/"..name)
  if items then
    for k,v in pairs(items) do
      cfg.items[k] = v
    end
  else
    print("[vRP] item pack ["..name.."] not found")
  end
end

load_item_pack("required")
load_item_pack("food")
load_item_pack("drugs")

return cfg
